// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbG0CNUCIePGMC7IIUv3SEGHMebTr9G0',
    appId: '1:611398646443:web:c2145719b0765f0bfd55ee',
    messagingSenderId: '611398646443',
    projectId: 'app-unaerp-odonto',
    authDomain: 'app-unaerp-odonto.firebaseapp.com',
    storageBucket: 'app-unaerp-odonto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8YomVKq7zFWFqmo5zBP8uWNNxXokuQmc',
    appId: '1:611398646443:android:318d35bb47a01fddfd55ee',
    messagingSenderId: '611398646443',
    projectId: 'app-unaerp-odonto',
    storageBucket: 'app-unaerp-odonto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBARF8KcEHnB8yTH3Bbx_yO2UeBx5DtaX0',
    appId: '1:611398646443:ios:57f3611c8ba6b859fd55ee',
    messagingSenderId: '611398646443',
    projectId: 'app-unaerp-odonto',
    storageBucket: 'app-unaerp-odonto.appspot.com',
    iosBundleId: 'com.example.appOdonto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBARF8KcEHnB8yTH3Bbx_yO2UeBx5DtaX0',
    appId: '1:611398646443:ios:57f3611c8ba6b859fd55ee',
    messagingSenderId: '611398646443',
    projectId: 'app-unaerp-odonto',
    storageBucket: 'app-unaerp-odonto.appspot.com',
    iosBundleId: 'com.example.appOdonto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATbG0CNUCIePGMC7IIUv3SEGHMebTr9G0',
    appId: '1:611398646443:web:1cb8b2ea7f5cd9b7fd55ee',
    messagingSenderId: '611398646443',
    projectId: 'app-unaerp-odonto',
    authDomain: 'app-unaerp-odonto.firebaseapp.com',
    storageBucket: 'app-unaerp-odonto.appspot.com',
  );
}
